version: '3'

services:

  omero-db:
    image: postgres:9.6.12-alpine
    networks:
      deephealth:
        aliases:
          - ome-pg-server
    environment:
      - POSTGRES_DB=omero
      - POSTGRES_USER=omero
      - POSTGRES_PASSWORD=omero
    volumes:
      - ./ome-pg-data:/var/lib/postgresql/data

  redis-server:
    image: redis:6.0.3-alpine
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      deephealth:
        aliases:
          - redis-server
    volumes:
      - ./redis-data:/data

  omero-server:
    image: openmicroscopy/omero-server:5.6.3-3
    depends_on:
      - omero-db
    networks:
      deephealth:
        aliases:
          - omero-server
    environment:
      - ROOTPASS=omero
      - CONFIG_omero_db_host=ome-pg-server
      - CONFIG_omero_db_user=omero
      - CONFIG_omero_db_pass=omero
      - CONFIG_omero_db_name=omero
      - ome-server-var:/opt/omero/server/OMERO.server/var

  omeseadragon:
    image: crs4/ome_seadragon-web:0.8.4-ome5.11-rc2
    depends_on:
      - omero-server
      - redis-server
    entrypoint: ['/usr/local/bin/wait-for-it.sh', 'redis-server:6379', '--',
                 '/usr/local/bin/wait-for-it.sh', 'omero-server:4063', '--timeout=600', '--strict', '--',
                 '/usr/local/bin/wait-for-it.sh', 'omero-server:4064', '--timeout=600', '--strict', '--',
                 '/usr/local/bin/entrypoint.sh']
    networks:
      deephealth:
    environment:
      - ROOTPASS=omero
      - OMEROHOST=omero-server
      - REDISHOST=redis-server
      - IMAGES_REPOSITORY=/OMERO/
      - MIRAX_FOLDER=/data/MIRAX
      - DATASETS_REPOSITORY=${PREDICTIONS_DIR}
      - GW_USER_NAME=ome_gw
      - GW_USER_PASS=omero

    volumes:
      - ${CWL_INPUTS_FOLDER}:/OMERO:ro
      # - /mnt/tdm-dic/docker_volumes/ome_seadragon_mirax:/data/MIRAX:ro
      - ${PREDICTIONS_DIR}:${PREDICTIONS_DIR}:rw
      - ${CWL_INPUTS_FOLDER}:/data/MIRAX:ro

  omeseadragon-nginx:
    # build: /opt/git/ome_seadragon-nginx-docker
    image: crs4/ome_seadragon-nginx:0.8.3-ome5.11
    depends_on:
      - omeseadragon
    entrypoint: ['/usr/local/bin/wait-for-it.sh', 'omeseadragon:4080', '--timeout=600', '--strict', '--',
                 '/usr/local/bin/entrypoint.sh']
    networks:
      deephealth:
    environment:
      - OMEROWEBHOST=omeseadragon
      # - VIRTUAL_HOST=ome-seadragon.mobydick

  promort-db:
    image: postgres:9.6.12-alpine
    networks:
      deephealth:
        aliases:
          - promort-db
    environment:
      - POSTGRES_DB=${PROMORT_DB}
      - POSTGRES_USER=${PROMORT_DB_USER}
      - POSTGRES_PASSWORD=${PROMORT_DB_PASSWORD}
    volumes:
      - ./data/promort-pg-data:/var/lib/postgresql/data

  promort-web:

    image: ${PROMORT_IMG:-promort-web}
    build:
      context: ./build/promort
      args:
        PROMORT_REPO: $PROMORT_REPO
        PROMORT_BRANCH: $PROMORT_BRANCH
    depends_on: 
      - promort-db
    entrypoint: ['/usr/local/bin/wait-for-it.sh', 'promort-db:5432', '--',
                 '/usr/local/bin/entrypoint.sh']
    networks:
      deephealth:
    environment:
      - DJANGO_CONFIG_FILE=/opt/django/conf/config.yaml
      - PROMORT_USER=${PROMORT_USER}
      - PROMORT_PASSWORD=${PROMORT_PASSWORD}
      - PROMORT_SESSION_ID=${PROMORT_SESSION_ID}

    volumes:
      - ./promort_config/:/opt/django/conf/
      - ./scripts/:/scripts/
      - ./scripts/promort/81_create_user.sh:/startup/81_create_user.sh

  promort-nginx:
    image: crs4/promort-nginx:0.9.3
    depends_on:
      - promort-web
    entrypoint: ['/usr/local/bin/wait-for-it.sh', 'promort-web:8080', '--timeout=600', '--strict', '--',
                 '/usr/local/bin/entrypoint.sh']
    networks:
      deephealth:
    environment:
      - DJANGO_SERVER=promort-web

