  name: build

  on:
    push:
      branches: [ master, develop, feat/CI ]
    pull_request:
      branches: [ master, develop ]

  jobs:
    build:
      runs-on: ubuntu-latest
      env:
        POETRY_VIRTUALENVS_CREATE: false

      steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8' 

      - name: install deps
        run: |
          pip install poetry
          sudo apt install jq

      - name: test
        run: tests/run.sh

      # - name: Bump version and push tag
      #   id: tag-creation
      #   uses: anothrNick/github-tag-action@1.34.0
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     WITH_V: true
      #

